/**
 * Supabase Edge Function: seed-generator
 *
 * Zamanlanmış (cron) çağrılır — Supabase Dashboard → Edge Functions → Schedules.
 * Önerilen aralık: günde 1 (0 6 * * *, örn. sabah 06:00 UTC).
 *
 * Replaces the old flat 26-template generic seed pool (same body text
 * dropped everywhere regardless of neighborhood — the thing that made
 * seeded questions feel obviously repetitive/AI-generated) with a
 * district-specific pool generated by Claude Haiku, one small batch per
 * active district per day ("generate once, serve many" — run_seed_drop
 * then just picks from this cached pool instead of calling the LLM live
 * per user per drop).
 *
 * Falls back gracefully: run_seed_drop still uses the old generic
 * seed_templates pool for any district that doesn't have pool coverage
 * yet (brand new area, or this function hasn't run since users showed up
 * there) — this function only ever ADDS district-specific content, never
 * removes the fallback.
 *
 * Required secrets (set via Supabase Dashboard → Edge Functions → Secrets,
 * or `supabase secrets set`):
 *   SUPABASE_URL                 (already set for seed-dropper/send-push)
 *   SUPABASE_SERVICE_ROLE_KEY    (already set for seed-dropper/send-push)
 *   ANTHROPIC_API_KEY            (NEW — get one at console.anthropic.com)
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
);

const ANTHROPIC_API_KEY = Deno.env.get('ANTHROPIC_API_KEY');
const MODEL = 'claude-haiku-4-5-20251001';

// Top up any district whose UNUSED pool has fallen below this.
const POOL_FLOOR = 4;
// New questions requested per district per top-up call.
const BATCH_SIZE = 8;
// Cap districts processed per run — cost/time control.
const MAX_DISTRICTS_PER_RUN = 15;

const SYSTEM_PROMPT = `You write short, hyperlocal social-app questions for Lore, a Turkish anonymous neighborhood Q&A app (like a mix of Nextdoor and Yik Yak, but map-based — people see and answer questions from others physically near them).

You are given ONE district/city name. Write questions a REAL PERSON who actually lives there might post to their neighbors — never a tourist-guide tone, never a customer-service tone.

STRICT RULES:
- Write in Turkish, natural and casual — contractions, everyday phrasing, the way a person actually types on their phone, not formal written Turkish.
- NEVER invent a specific business, cafe, restaurant, street, or landmark name you weren't given. You were NOT given any real place names — refer to categories generically ("mahalledeki fırın", "şu köşedeki büfe") if needed, never a made-up proper noun.
- NEVER use these clichéd openers/phrases: "Bu çevrede", "Buralarda", "Bu mahallede" as a sentence-starting crutch on every question — vary how each question opens. Do not overuse the vague "buralarda/bu çevrede" framing that makes every question sound like a template.
- NEVER write generic "is there X nearby" business-lookup questions (pharmacy/cafe/parking/gym) as your default. At most 1 of your batch may be that type — the rest must be genuine opinions, debates, curiosities, or personal takes about the area.
- Vary sentence length and structure. Mix short blunt questions with longer, more specific ones. Don't make every question the same shape.
- Each question must feel like it could ONLY be about this specific kind of place — reference the district's plausible character (dense/quiet, coastal/inland, student/family/business area, based on what you know about that name) without asserting invented facts.

ARCHETYPES to rotate through (use a good mix across the batch, label each with one of these keys):
- opinion: a hot-take or opinion about living there ("burada yaşamanın en can sıkıcı yanı ne?")
- would_you_rather: two neighborhood-flavored tradeoffs
- curiosity: mild curiosity about neighbors/area ("bu sokakta oturanlar aslında ne iş yapıyor sizce?")
- debate: a mildly controversial local topic (parking, construction, rent, noise)
- nostalgia: "burası eskiden nasıldı" / how the area has changed
- newcomer: helpful-but-personal, for someone who just moved there
- seasonal: grounded in the REAL current date/season/weekday given to you in the user message (never invent a season or event — use exactly what you're told)
- confession: a small, relatable local confession/AITA-style question
- lookup: (use sparingly, max 1 per batch) a genuine "does X exist nearby" business-category question

Respond with ONLY a JSON array, no prose before or after, no markdown fences. Each item:
{"type": "vote"|"choice"|"open", "body": "...", "archetype": "...", "options": ["...", "..."] }
- "options" ONLY for type "choice" — exactly 2 to 4 short option labels (each under 20 characters), NOT for "vote" or "open".
- "body" max 120 characters.
- Every item must have a DIFFERENT archetype from the others in the batch where possible.`;

const FEW_SHOT_EXAMPLES = `Örnek (Kadıköy, İstanbul için, sadece stil referansı — bunları tekrar üretme):
[
  {"type":"open","body":"Bu sokaklarda büyüyenler şimdi nerede yaşıyor sizce, hala buralarda mı?","archetype":"curiosity"},
  {"type":"vote","body":"Vapur iskelesine yürüyerek gitmek mi daha keyifli, dolmuşla mı?","archetype":"opinion"},
  {"type":"choice","body":"Akşamüstü buralarda en çok neye denk gelirsin?","archetype":"seasonal","options":["Kalabalık vapur","Trafik","Boş sokaklar","Müzik sesi"]},
  {"type":"open","body":"Burada 10 yıl önce ne vardı da şimdi yok, en çok neyi özlüyorsun?","archetype":"nostalgia"},
  {"type":"vote","body":"Komşuların gürültüsünden şikayet etmek ayıp mı sence?","archetype":"confession"}
]`;

interface GeneratedQuestion {
  type: 'vote' | 'choice' | 'open';
  body: string;
  archetype?: string;
  options?: string[];
}

const TR_MONTHS = [
  'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
  'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık',
];
const TR_WEEKDAYS = ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'];

/**
 * Real (not invented) date context so the "seasonal" archetype can
 * reference an actual current moment (weather season, weekday, a notable
 * recurring period) instead of a generic, could-be-any-time-of-year
 * question — closes the "seasonal/event-based content" gap from the
 * retention research. Deliberately limited to safe, always-true Gregorian
 * facts (month/season/weekday) rather than attempting a precise religious
 * or school-calendar lookup, which risks asserting a wrong date to users.
 */
function getSeasonalContext(): string {
  const now = new Date();
  const month = now.getUTCMonth(); // 0-11
  const monthName = TR_MONTHS[month];
  const weekday = TR_WEEKDAYS[now.getUTCDay()];
  const isWeekend = now.getUTCDay() === 0 || now.getUTCDay() === 6;

  let season: string;
  if ([11, 0, 1].includes(month)) season = 'kış';
  else if ([2, 3, 4].includes(month)) season = 'ilkbahar';
  else if ([5, 6, 7].includes(month)) season = 'yaz';
  else season = 'sonbahar';

  const notes: string[] = [];
  if (month === 8) notes.push('okulların yeni açıldığı dönem');
  if (month === 11) notes.push('yılın sonuna yaklaşılıyor, yeni yıl havası');
  if ([5, 6, 7].includes(month)) notes.push('yaz sıcağı, tatil dönemi');
  if (month === 4) notes.push('bahar, hava ısınıyor');

  return `Bugün ${monthName}, ${weekday} (${isWeekend ? 'hafta sonu' : 'hafta içi'}), mevsim: ${season}.${notes.length ? ' Not: ' + notes.join(', ') + '.' : ''}`;
}

async function generateForDistrict(districtLabel: string): Promise<GeneratedQuestion[]> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 1200,
      system: SYSTEM_PROMPT,
      messages: [
        { role: 'user', content: FEW_SHOT_EXAMPLES },
        { role: 'assistant', content: 'Anladım, bu stili takip edeceğim ama örnekteki soruları birebir tekrarlamayacağım.' },
        {
          role: 'user',
          content: `District: ${districtLabel}\n${getSeasonalContext()}\n\n${BATCH_SIZE} tane farklı, çeşitli arketiplerden soru üret. "seasonal" arketipindeki soru(lar) yukarıdaki gerçek tarih/mevsim bilgisini yansıtsın (örn. kış ayında "deniz sıcak mı" gibi mevsimsiz bir soru yazma).`,
        },
      ],
    }),
  });

  if (!res.ok) {
    throw new Error(`Anthropic API error ${res.status}: ${await res.text()}`);
  }

  const json = await res.json();
  const text: string = json?.content?.[0]?.text ?? '[]';

  // Haiku occasionally wraps JSON in a fenced block despite instructions —
  // strip fences before parsing rather than failing the whole batch.
  const cleaned = text.trim().replace(/^```(?:json)?/i, '').replace(/```$/, '').trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];

  return (parsed as any[]).filter((q) =>
    q && typeof q.body === 'string' && q.body.length > 0 && q.body.length <= 120 &&
    ['vote', 'choice', 'open'].includes(q.type),
  );
}

function toOptionsJson(q: GeneratedQuestion): { label: string; count: number }[] | null {
  if (q.type === 'vote') {
    return [{ label: 'Evet', count: 0 }, { label: 'Hayır', count: 0 }];
  }
  if (q.type === 'choice') {
    const opts = (q.options ?? []).filter((o) => typeof o === 'string' && o.trim().length > 0 && o.length <= 20);
    if (opts.length < 2) return null; // invalid choice question — drop it
    return opts.slice(0, 4).map((label) => ({ label, count: 0 }));
  }
  return null; // open
}

Deno.serve(async () => {
  if (!ANTHROPIC_API_KEY) {
    return new Response(JSON.stringify({ ok: false, error: 'ANTHROPIC_API_KEY secret not set' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Districts with active users whose unused pool has fallen below the floor.
  const { data: districts, error: districtsErr } = await supabase.rpc('districts_needing_seed_pool', {
    p_floor: POOL_FLOOR,
    p_limit: MAX_DISTRICTS_PER_RUN,
  });

  if (districtsErr) {
    return new Response(JSON.stringify({ ok: false, error: districtsErr.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  let districtsProcessed = 0;
  let questionsInserted = 0;

  for (const row of (districts ?? []) as { district_label: string }[]) {
    try {
      const generated = await generateForDistrict(row.district_label);
      if (generated.length === 0) continue;

      const rows = generated
        .map((q) => ({
          district_label: row.district_label,
          body: q.body,
          type: q.type,
          options: toOptionsJson(q),
          archetype: q.archetype ?? null,
        }))
        .filter((r) => r.type === 'open' || r.options !== null);

      if (rows.length === 0) continue;

      const { error: insertErr } = await supabase.from('seed_pool').insert(rows);
      if (insertErr) {
        console.error(`seed_pool insert error for ${row.district_label}:`, insertErr);
        continue;
      }

      districtsProcessed++;
      questionsInserted += rows.length;
    } catch (e) {
      console.error(`generateForDistrict failed for ${row.district_label}:`, e);
    }
  }

  return new Response(JSON.stringify({ ok: true, districtsProcessed, questionsInserted }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
});
