/**
 * Supabase Edge Function: seed-generator
 *
 * Zamanlanmış (cron) çağrılır — Supabase Dashboard → Edge Functions → Schedules.
 * Önerilen aralık: günde 1 (0 6 * * *, örn. sabah 06:00 UTC).
 *
 * Replaces the old flat 26-template generic seed pool (same body text
 * dropped everywhere regardless of neighborhood — the thing that made
 * seeded questions feel obviously repetitive/AI-generated) with a
 * district-specific pool generated by Claude Haiku, one small batch per
 * active district per day ("generate once, serve many" — run_seed_drop
 * then just picks from this cached pool instead of calling the LLM live
 * per user per drop).
 *
 * Falls back gracefully: run_seed_drop still uses the old generic
 * seed_templates pool for any district that doesn't have pool coverage
 * yet (brand new area, or this function hasn't run since users showed up
 * there) — this function only ever ADDS district-specific content, never
 * removes the fallback.
 *
 * Required secrets (set via Supabase Dashboard → Edge Functions → Secrets,
 * or `supabase secrets set`):
 *   SUPABASE_URL                 (already set for seed-dropper/send-push)
 *   SUPABASE_SERVICE_ROLE_KEY    (already set for seed-dropper/send-push)
 *   ANTHROPIC_API_KEY            (NEW — get one at console.anthropic.com)
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
);

const ANTHROPIC_API_KEY = Deno.env.get('ANTHROPIC_API_KEY');
const MODEL = 'claude-haiku-4-5-20251001';

// Top up any district whose UNUSED pool has fallen below this.
const POOL_FLOOR = 4;
// New questions requested per district per top-up call.
const BATCH_SIZE = 8;
// Cap districts processed per run — cost/time control.
const MAX_DISTRICTS_PER_RUN = 15;

const SYSTEM_PROMPT = `You write short, hyperlocal social-app questions for Lore, a global anonymous neighborhood Q&A app (like a mix of Nextdoor and Yik Yak, but map-based — people see and answer questions from others physically near them).

You are given ONE district/city name. Write questions a REAL PERSON who actually lives there might post to their neighbors — never a tourist-guide tone, never a customer-service tone.

LANGUAGE — read carefully:
- First, silently determine the natural everyday language of the people who live in the given district/city (e.g. Kadıköy/İstanbul → Turkish, Berlin → German, Paris → French, a generic or ambiguous English-speaking city → English).
- Write the ENTIRE batch — every question body AND every option label — in that local language, natural and casual: contractions, everyday phrasing, the way a real local person actually types on their phone, never formal/written-register language.
- If you cannot confidently identify the local language for the given name, default to English.
- Never mix languages within one question.

STRICT RULES:
- NEVER invent a specific business, cafe, restaurant, street, or landmark name you weren't given. You were NOT given any real place names — refer to categories generically (e.g. "the bakery in the neighborhood", "that corner shop") if needed, never a made-up proper noun.
- NEVER use a translated equivalent of "Around here", "In this neighborhood", "In this area" as a sentence-starting crutch on every question — vary how each question opens. Do not overuse that vague framing that makes every question sound like a template.
- NEVER write generic "is there X nearby" business-lookup questions (pharmacy/cafe/parking/gym) as your default. At most 1 of your batch may be that type — the rest must be genuine opinions, debates, curiosities, or personal takes about the area.
- Vary sentence length and structure. Mix short blunt questions with longer, more specific ones. Don't make every question the same shape.
- Each question must feel like it could ONLY be about this specific kind of place — reference the district's plausible character (dense/quiet, coastal/inland, student/family/business area, based on what you know about that name) without asserting invented facts.

ARCHETYPES to rotate through (use a good mix across the batch, label each with one of these keys):
- opinion: a hot-take or opinion about living there
- would_you_rather: two neighborhood-flavored tradeoffs
- curiosity: mild curiosity about neighbors/area
- debate: a mildly controversial local topic (parking, construction, rent, noise)
- nostalgia: "what was this place like before" / how the area has changed
- newcomer: helpful-but-personal, for someone who just moved there
- seasonal: grounded in the REAL current date/season/weekday given to you in the user message (never invent a season or event — use exactly what you're told; if the given city is in the Southern Hemisphere, invert the season accordingly)
- confession: a small, relatable local confession/AITA-style question
- lookup: (use sparingly, max 1 per batch) a genuine "does X exist nearby" business-category question

Respond with ONLY a JSON array, no prose before or after, no markdown fences. Each item:
{"type": "vote"|"choice"|"open", "body": "...", "archetype": "...", "options": ["...", "..."] }
- "options" is REQUIRED for "vote" (exactly 2 labels — that language's natural equivalent of "Yes"/"No") and "choice" (2 to 4 short labels, each under 20 characters), and OMITTED for "open".
- "body" max 120 characters.
- Every item must have a DIFFERENT archetype from the others in the batch where possible.`;

const FEW_SHOT_EXAMPLES = `Example (for Kadıköy, İstanbul — a style/format reference only, in the language that city calls for; never repeat these verbatim, and always match the batch's own language to whatever city you're actually given):
[
  {"type":"open","body":"Bu sokaklarda büyüyenler şimdi nerede yaşıyor sizce, hala buralarda mı?","archetype":"curiosity"},
  {"type":"vote","body":"Vapur iskelesine yürüyerek gitmek mi daha keyifli, dolmuşla mı?","archetype":"opinion","options":["Evet","Hayır"]},
  {"type":"choice","body":"Akşamüstü buralarda en çok neye denk gelirsin?","archetype":"seasonal","options":["Kalabalık vapur","Trafik","Boş sokaklar","Müzik sesi"]},
  {"type":"open","body":"Burada 10 yıl önce ne vardı da şimdi yok, en çok neyi özlüyorsun?","archetype":"nostalgia"},
  {"type":"vote","body":"Komşuların gürültüsünden şikayet etmek ayıp mı sence?","archetype":"confession","options":["Evet","Hayır"]}
]`;

interface GeneratedQuestion {
  type: 'vote' | 'choice' | 'open';
  body: string;
  archetype?: string;
  options?: string[];
}

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

/**
 * Real (not invented) date context so the "seasonal" archetype can
 * reference an actual current moment (weather season, weekday, a notable
 * recurring period) instead of a generic, could-be-any-time-of-year
 * question — closes the "seasonal/event-based content" gap from the
 * retention research. Deliberately limited to safe, always-true Gregorian
 * facts (month/season/weekday) rather than attempting a precise religious
 * or school-calendar lookup, which risks asserting a wrong date to users.
 *
 * Kept in English regardless of the target district's language — this is
 * factual input for the model, not output; the model translates/localizes
 * it into whatever language it's writing the batch in (see SYSTEM_PROMPT's
 * LANGUAGE section), and inverts the season itself for Southern Hemisphere
 * cities.
 */
function getSeasonalContext(): string {
  const now = new Date();
  const month = now.getUTCMonth(); // 0-11
  const monthName = MONTHS[month];
  const weekday = WEEKDAYS[now.getUTCDay()];
  const isWeekend = now.getUTCDay() === 0 || now.getUTCDay() === 6;

  let season: string; // Northern Hemisphere; invert for Southern Hemisphere cities
  if ([11, 0, 1].includes(month)) season = 'winter';
  else if ([2, 3, 4].includes(month)) season = 'spring';
  else if ([5, 6, 7].includes(month)) season = 'summer';
  else season = 'autumn';

  const notes: string[] = [];
  if (month === 8) notes.push('schools just started the new term');
  if (month === 11) notes.push('year-end, new year mood approaching');
  if ([5, 6, 7].includes(month)) notes.push('summer heat, holiday season');
  if (month === 4) notes.push('spring, weather warming up');

  return `Today is ${monthName}, ${weekday} (${isWeekend ? 'weekend' : 'weekday'}), Northern Hemisphere season: ${season}.${notes.length ? ' Note: ' + notes.join(', ') + '.' : ''}`;
}

async function generateForDistrict(districtLabel: string): Promise<GeneratedQuestion[]> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 1200,
      system: SYSTEM_PROMPT,
      messages: [
        { role: 'user', content: FEW_SHOT_EXAMPLES },
        { role: 'assistant', content: "Understood — I'll follow this style and format, adapt the language to whichever district I'm given, and never repeat the example questions verbatim." },
        {
          role: 'user',
          content: `District: ${districtLabel}\n${getSeasonalContext()}\n\nGenerate ${BATCH_SIZE} different questions across a good mix of archetypes, in the local language of the given district. Any "seasonal" archetype question(s) must reflect the real date/season info above (e.g. don't write a season-agnostic "is the sea warm" question in winter).`,
        },
      ],
    }),
  });

  if (!res.ok) {
    throw new Error(`Anthropic API error ${res.status}: ${await res.text()}`);
  }

  const json = await res.json();
  const text: string = json?.content?.[0]?.text ?? '[]';

  // Haiku occasionally wraps JSON in a fenced block despite instructions —
  // strip fences before parsing rather than failing the whole batch.
  const cleaned = text.trim().replace(/^```(?:json)?/i, '').replace(/```$/, '').trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];

  return (parsed as any[]).filter((q) =>
    q && typeof q.body === 'string' && q.body.length > 0 && q.body.length <= 120 &&
    ['vote', 'choice', 'open'].includes(q.type),
  );
}

function toOptionsJson(q: GeneratedQuestion): { label: string; count: number }[] | null {
  if (q.type === 'vote') {
    // Model supplies the localized Yes/No pair (see LANGUAGE section of
    // SYSTEM_PROMPT) — never hardcode a language here. Falls back to
    // English if it somehow omitted them.
    const opts = (q.options ?? []).filter((o) => typeof o === 'string' && o.trim().length > 0 && o.length <= 20);
    if (opts.length >= 2) return opts.slice(0, 2).map((label) => ({ label, count: 0 }));
    return [{ label: 'Yes', count: 0 }, { label: 'No', count: 0 }];
  }
  if (q.type === 'choice') {
    const opts = (q.options ?? []).filter((o) => typeof o === 'string' && o.trim().length > 0 && o.length <= 20);
    if (opts.length < 2) return null; // invalid choice question — drop it
    return opts.slice(0, 4).map((label) => ({ label, count: 0 }));
  }
  return null; // open
}

Deno.serve(async () => {
  if (!ANTHROPIC_API_KEY) {
    return new Response(JSON.stringify({ ok: false, error: 'ANTHROPIC_API_KEY secret not set' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Districts with active users whose unused pool has fallen below the floor.
  const { data: districts, error: districtsErr } = await supabase.rpc('districts_needing_seed_pool', {
    p_floor: POOL_FLOOR,
    p_limit: MAX_DISTRICTS_PER_RUN,
  });

  if (districtsErr) {
    return new Response(JSON.stringify({ ok: false, error: districtsErr.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  let districtsProcessed = 0;
  let questionsInserted = 0;

  for (const row of (districts ?? []) as { district_label: string }[]) {
    try {
      const generated = await generateForDistrict(row.district_label);
      if (generated.length === 0) continue;

      const rows = generated
        .map((q) => ({
          district_label: row.district_label,
          body: q.body,
          type: q.type,
          options: toOptionsJson(q),
          archetype: q.archetype ?? null,
        }))
        .filter((r) => r.type === 'open' || r.options !== null);

      if (rows.length === 0) continue;

      const { error: insertErr } = await supabase.from('seed_pool').insert(rows);
      if (insertErr) {
        console.error(`seed_pool insert error for ${row.district_label}:`, insertErr);
        continue;
      }

      districtsProcessed++;
      questionsInserted += rows.length;
    } catch (e) {
      console.error(`generateForDistrict failed for ${row.district_label}:`, e);
    }
  }

  return new Response(JSON.stringify({ ok: true, districtsProcessed, questionsInserted }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
});
