"""Deterministic Claude Ads contracts and scoring engine."""

from .contracts import ContractError, load_contract, validate_contract
from .control_registry import (
    ControlRegistry,
    RegistryEntry,
    RegistryError,
    ScoringProfile,
    load_control_registry,
)
from .adapters import Adapter, AdapterCapabilities, GenericCSVExportAdapter, MutationDisabledError
from .models import AccountSnapshot, ControlDefinition, Finding, ReportBundle, RunManifest
from .orchestration import (
    OrchestrationError,
    OrchestrationStore,
    artifact_sha256,
    canonical_json_bytes,
    evaluate_artifact_gate,
)
from .workflow_models import (
    BrandProfile,
    CreativeBrief,
    DataLifecycle,
    ExperimentArtifact,
    GenerationManifest,
    MediaPlan,
    MonitoringBundle,
    MutationPlan,
    OrchestrationGate,
    OrchestrationResult,
    OrchestrationRun,
    OrchestrationTask,
    SetupProfile,
)
from .reporting import (
    PDFDependencyError,
    ReportRenderError,
    atomic_write_report,
    render_html,
    render_markdown,
    render_pdf,
    render_report,
    resolve_report_path,
    write_report_bundle,
)
from .product_status import ProductStatusError, evaluate_product_status
from .scoring import (
    CATEGORY_WEIGHT_TOTAL,
    SEVERITY_WEIGHTS,
    PortfolioResult,
    ScoreResult,
    ScoringError,
    score_account,
    score_portfolio,
)

__all__ = [
    "CATEGORY_WEIGHT_TOTAL",
    "SEVERITY_WEIGHTS",
    "AccountSnapshot",
    "Adapter",
    "AdapterCapabilities",
    "ContractError",
    "ControlRegistry",
    "ControlDefinition",
    "Finding",
    "GenericCSVExportAdapter",
    "MutationDisabledError",
    "MutationPlan",
    "MonitoringBundle",
    "MediaPlan",
    "GenerationManifest",
    "ExperimentArtifact",
    "CreativeBrief",
    "DataLifecycle",
    "BrandProfile",
    "SetupProfile",
    "OrchestrationError",
    "OrchestrationGate",
    "OrchestrationResult",
    "OrchestrationRun",
    "OrchestrationStore",
    "OrchestrationTask",
    "PDFDependencyError",
    "PortfolioResult",
    "ProductStatusError",
    "ReportRenderError",
    "ReportBundle",
    "RegistryEntry",
    "RegistryError",
    "RunManifest",
    "ScoreResult",
    "ScoringError",
    "ScoringProfile",
    "load_contract",
    "load_control_registry",
    "atomic_write_report",
    "render_html",
    "render_markdown",
    "render_pdf",
    "render_report",
    "resolve_report_path",
    "score_account",
    "score_portfolio",
    "validate_contract",
    "evaluate_product_status",
    "artifact_sha256",
    "canonical_json_bytes",
    "evaluate_artifact_gate",
    "write_report_bundle",
]

__version__ = "2.0.0"
